-- MARCH - DECEMBER 2026: AIR SIGNS (Gemini, Libra, Aquarius)
-- Categories: Love, Money, Career, Family, Health

-- GEMINI 2026 (MARCH - DECEMBER)
INSERT INTO zodiac_predictions_2026 (sign, month_id, category, prediction) VALUES 
('Gemini', 3, 'Love', 'The eclipse highlights a career/love choice. Be honest.'),
('Gemini', 3, 'Money', 'A sudden shift in your professional income. Budget for change.'),
('Gemini', 3, 'Career', 'A major career peak. You receive an award or public honor.'),
('Gemini', 3, 'Family', 'Your professional life impacts home. Communicate with family.'),
('Gemini', 3, 'Health', 'Watch for stress-related headaches. Prioritize relaxation.'),
('Gemini', 4, 'Love', 'Social connections slow down. Revisit an old friendship.'),
('Gemini', 4, 'Money', 'Wait until late month to finalize major group financial deals.'),
('Gemini', 4, 'Career', 'Team projects are delayed. Use the time for solo research.'),
('Gemini', 4, 'Family', 'Misunderstandings with friends who are like family.'),
('Gemini', 4, 'Health', 'Focus on respiratory health. Air quality is important for you.'),
('Gemini', 5, 'Love', 'Private feelings resurface. Enjoy a quiet, hidden romance.'),
('Gemini', 5, 'Money', 'A secret financial opportunity may arise. Keep it quiet.'),
('Gemini', 5, 'Career', 'Work behind the scenes is productive. Avoid the spotlight.'),
('Gemini', 5, 'Family', 'Quiet time at home. Inner reflection and family history.'),
('Gemini', 5, 'Health', 'Prioritize rest and mental health. Meditation is a key tool.'),
('Gemini', 6, 'Love', 'Happy birthday! You are radiant and attracting new interest.'),
('Gemini', 6, 'Money', 'Financial gifts or bonuses. Your personal brand brings profit.'),
('Gemini', 6, 'Career', 'A major breakthrough. You are given a green light for a project.'),
('Gemini', 6, 'Family', 'You are the focus of celebrations. Harmonious family month.'),
('Gemini', 6, 'Health', 'Vitality returns. Great for a physical makeover or new diet.'),
('Gemini', 7, 'Love', 'Sensual and grounded. You enjoy quality time with a partner.'),
('Gemini', 7, 'Money', 'A highly profitable month. Your income increases significantly.'),
('Gemini', 7, 'Career', 'Practical skills are in demand. You finalize a solid deal.'),
('Gemini', 7, 'Family', 'Focus on home security and stability. Peaceful atmosphere.'),
('Gemini', 7, 'Health', 'Excellent stamina. Focus on neck and throat. Stay hydrated.'),
('Gemini', 8, 'Love', 'The eclipse forces a look at your home life and partnership.'),
('Gemini', 8, 'Money', 'Large expenses on property or family. Check insurance.'),
('Gemini', 8, 'Career', 'A career transition is possible. Change your environment.'),
('Gemini', 8, 'Family', 'A sudden move or renovation. Family members restless.'),
('Gemini', 8, 'Health', 'Watch for stress-related digestive issues. Clean eating.'),
('Gemini', 9, 'Love', 'Romantic and fun! Dates, hobbies, and creativity flourish.'),
('Gemini', 9, 'Money', 'Luck is on your side. Small win or creative venture pays off.'),
('Gemini', 9, 'Career', 'A creative project is a success. Praised for unique vision.'),
('Gemini', 9, 'Family', 'Joyful news regarding children or family expansion.'),
('Gemini', 9, 'Health', 'Great month for fun fitness—dance or team sports.'),
('Gemini', 10, 'Love', 'Commitment is the theme. Work toward a shared goal.'),
('Gemini', 10, 'Money', 'Steady financial gains through partnership or joint ventures.'),
('Gemini', 10, 'Career', 'Meticulous attention to detail earns you high praise.'),
('Gemini', 10, 'Family', 'Routine home life is peaceful. Joy in daily tasks.'),
('Gemini', 10, 'Health', 'Focus on gut health and routine. Medical check-up favored.'),
('Gemini', 11, 'Love', 'Deep intimacy. You and your partner share a profound bond.'),
('Gemini', 11, 'Money', 'A windfall from a joint source or investment is likely.'),
('Gemini', 11, 'Career', 'Strategic work behind the scenes. Handle sensitivity well.'),
('Gemini', 11, 'Family', 'Deep emotional healing. A long-standing issue resolved.'),
('Gemini', 11, 'Health', 'Focus on hormonal balance and reproductive health.'),
('Gemini', 12, 'Love', 'Expansion through shared travel or philosophy. Fated meeting.'),
('Gemini', 12, 'Money', 'Funds for travel or higher learning are secured easily.'),
('Gemini', 12, 'Career', 'Take your skills to a wider market. Success in world fields.'),
('Gemini', 12, 'Family', 'Holiday spent traveling or with diverse family members.'),
('Gemini', 12, 'Health', 'Physical stamina is high. Adventurous end to 2026.');

-- LIBRA 2026 (MARCH - DECEMBER)
INSERT INTO zodiac_predictions_2026 (sign, month_id, category, prediction) VALUES 
('Libra', 3, 'Love', 'The eclipse highlights your work/health balance and love.'),
('Libra', 3, 'Money', 'A sudden shift in your daily income. Adjust your budget.'),
('Libra', 3, 'Career', 'Professional breakthroughs through health or service fields.'),
('Libra', 3, 'Family', 'Daily routine at home is disrupted. Find a new rhythm.'),
('Libra', 3, 'Health', 'Focus on your feet and immune system. Rest is needed.'),
('Libra', 4, 'Love', 'Relationship communication is slow. Revisit old agreements.'),
('Libra', 4, 'Money', 'Wait until late month to finalize major partnership deals.'),
('Libra', 4, 'Career', 'Negotiations are delayed. Use the time for fine-tuning.'),
('Libra', 4, 'Family', 'Misunderstandings with a spouse or close relative.'),
('Libra', 4, 'Health', 'Focus on lower back and kidney health. Stay hydrated.'),
('Libra', 5, 'Love', 'Deep intimacy. You and your partner share a profound bond.'),
('Libra', 5, 'Money', 'A windfall from a joint source or investment is likely.'),
('Libra', 5, 'Career', 'Strategic work behind the scenes. Handle sensitivity well.'),
('Libra', 5, 'Family', 'Deep emotional healing. A long-standing issue resolved.'),
('Libra', 5, 'Health', 'Focus on hormonal balance and reproductive health.'),
('Libra', 6, 'Love', 'Expansion through travel or learning with a partner.'),
('Libra', 6, 'Money', 'Income from a foreign source or teaching increases.'),
('Libra', 6, 'Career', 'Success in publishing, travel, or legal fields.'),
('Libra', 6, 'Family', 'A joyful family trip or event involving distance.'),
('Libra', 6, 'Health', 'Energy is high. Perfect for outdoor activities.'),
('Libra', 7, 'Love', 'Career success adds to your charisma. Workplace romance.'),
('Libra', 7, 'Money', 'A professional bonus or raise. Your net worth grows.'),
('Libra', 7, 'Career', 'The "Golden Window." You reach a new career height.'),
('Libra', 7, 'Family', 'Your success celebrated. Harmonious family atmosphere.'),
('Libra', 7, 'Health', 'Physical vitality at a peak. Strong and capable.'),
('Libra', 8, 'Love', 'The eclipse forces a relationship turning point. Honesty.'),
('Libra', 8, 'Money', 'Financial tension with a partner. Keep accounts clear.'),
('Libra', 8, 'Career', 'A partner or collaborator exits. Opens a better door.'),
('Libra', 8, 'Family', 'Home life requires a delicate touch. Secret revealed.'),
('Libra', 8, 'Health', 'Stress affects digestion. Clean eating and meditation.'),
('Libra', 9, 'Love', 'Social life is vibrant. Meet someone through a group.'),
('Libra', 9, 'Money', 'Profitable networking. A friend provides a financial tip.'),
('Libra', 9, 'Career', 'Collaborative projects a success. Key team player.'),
('Libra', 9, 'Family', 'Joyful events with your extended family or community.'),
('Libra', 9, 'Health', 'Group fitness keeps you motivated and healthy.'),
('Libra', 10, 'Love', 'Happy birthday! You are magnetic and attracting interest.'),
('Libra', 10, 'Money', 'Financial gifts or bonuses. Personal brand brings profit.'),
('Libra', 10, 'Career', 'A major breakthrough. You are the boss of your destiny.'),
('Libra', 10, 'Family', 'You are the focus of celebrations. Harmonious month.'),
('Libra', 10, 'Health', 'Vitality returns. Physical makeover or new diet.'),
('Libra', 11, 'Love', 'Sensual and grounded. Quality time with a partner.'),
('Libra', 11, 'Money', 'A highly profitable month. Your income increases.'),
('Libra', 11, 'Career', 'Practical skills in demand. Finalize a solid deal.'),
('Libra', 11, 'Family', 'Focus on home security and stability. Peaceful.'),
('Libra', 11, 'Health', 'Excellent stamina. Focus on neck and throat.'),
('Libra', 12, 'Love', 'A short trip brings romance. Communication is deep.'),
('Libra', 12, 'Money', 'Small wins add up. Secondary income is reliable.'),
('Libra', 12, 'Career', 'Your ideas are valued. Great for marketing and writing.'),
('Libra', 12, 'Family', 'Peace returns home. Helping a younger member joy.'),
('Libra', 12, 'Health', 'Light cardio and fresh air. Adventurous end to 2026.');

-- AQUARIUS 2026 (MARCH - DECEMBER)
INSERT INTO zodiac_predictions_2026 (sign, month_id, category, prediction) VALUES 
('Aquarius', 3, 'Love', 'The eclipse highlights a romantic turning point. Truth.'),
('Aquarius', 3, 'Money', 'A sudden shift in speculative income. Be ready.'),
('Aquarius', 3, 'Career', 'A creative project is a success. Praised for vision.'),
('Aquarius', 3, 'Family', 'Joyful news regarding children or family expansion.'),
('Aquarius', 3, 'Health', 'Energy is high. Perfect for team sports or fun.'),
('Aquarius', 4, 'Love', 'Communication with a partner is slow. Revisit old plans.'),
('Aquarius', 4, 'Money', 'Wait until late month to sign major local financial deals.'),
('Aquarius', 4, 'Career', 'Writing or marketing projects delayed. Fine-tune them.'),
('Aquarius', 4, 'Family', 'Misunderstandings with neighbors or siblings.'),
('Aquarius', 4, 'Health', 'Focus on your arms and shoulders. Light stretching.'),
('Aquarius', 5, 'Love', 'Deeply emotional and cozy. Home joy with a partner.'),
('Aquarius', 5, 'Money', 'A beautiful month for home improvement and value.'),
('Aquarius', 5, 'Career', 'Working from home or privately proves very productive.'),
('Aquarius', 5, 'Family', 'Harmonious home life. Family traditions are joy.'),
('Aquarius', 5, 'Health', 'Focus on your core and back. Yoga is recommended.'),
('Aquarius', 6, 'Love', 'Romantic and fun! Dates, hobbies, and creativity.'),
('Aquarius', 6, 'Money', 'Luck is on your side. Small win or creative profit.'),
('Aquarius', 6, 'Career', 'A creative project is a success. Professional praise.'),
('Aquarius', 6, 'Family', 'Joyful news regarding family growth or kids.'),
('Aquarius', 6, 'Health', 'Great month for fun fitness—dance or group sports.'),
('Aquarius', 7, 'Love', 'Commitment is the theme. Work toward a shared goal.'),
('Aquarius', 7, 'Money', 'Steady financial gains through joint ventures.'),
('Aquarius', 7, 'Career', 'Meticulous attention to detail earns you high praise.'),
('Aquarius', 7, 'Family', 'Routine home life is peaceful. Joy in daily tasks.'),
('Aquarius', 7, 'Health', 'Focus on gut health. Medical check-up favored.'),
('Aquarius', 8, 'Love', 'The eclipse forces a look at your beliefs and partner.'),
('Aquarius', 8, 'Money', 'Large expenses on education or travel. Budget.'),
('Aquarius', 8, 'Career', 'A transition in your professional direction or market.'),
('Aquarius', 8, 'Family', 'A family member has a different vision for future.'),
('Aquarius', 8, 'Health', 'Watch for stress headaches. Prioritize fresh air.'),
('Aquarius', 9, 'Love', 'Deep intimacy. You and your partner share a bond.'),
('Aquarius', 9, 'Money', 'A windfall from a joint source or investment.'),
('Aquarius', 9, 'Career', 'Strategic work behind the scenes. Handle secrets well.'),
('Aquarius', 9, 'Family', 'Deep emotional healing. A long-standing issue resolved.'),
('Aquarius', 9, 'Health', 'Focus on hormonal balance and reproductive health.'),
('Aquarius', 10, 'Love', 'Expansion through shared travel or learning.'),
('Aquarius', 10, 'Money', 'Income from a foreign source or teaching increases.'),
('Aquarius', 10, 'Career', 'Success in publishing, travel, or legal fields.'),
('Aquarius', 10, 'Family', 'Joyful family trip or event involving distance.'),
('Aquarius', 10, 'Health', 'Energy is high. Perfect for outdoor activities.'),
('Aquarius', 11, 'Love', 'Career success adds to your charisma. Romance.'),
('Aquarius', 11, 'Money', 'A professional bonus or raise. Net worth grows.'),
('Aquarius', 11, 'Career', 'A breakthrough month. Reach a new career height.'),
('Aquarius', 11, 'Family', 'Your success celebrated. Harmonious atmosphere.'),
('Aquarius', 11, 'Health', 'Physical vitality at a peak. Strong and capable.'),
('Aquarius', 12, 'Love', 'Social life is vibrant. Meet someone through a friend.'),
('Aquarius', 12, 'Money', 'Profitable networking. A high-value financial tip.'),
('Aquarius', 12, 'Career', 'Collaborative projects a success. Key team player.'),
('Aquarius', 12, 'Family', 'Joyful events with your extended family.'),
('Aquarius', 12, 'Health', 'Group fitness keeps you motivated and healthy.');
