-- MARCH - DECEMBER 2026: FIRE SIGNS (Aries, Leo, Sagittarius)
-- Categories: Love, Money, Career, Family, Health

-- ARIES 2026
INSERT INTO zodiac_predictions_2026 (sign, month_id, category, prediction) VALUES 
('Aries', 3, 'Love', 'The March 3rd eclipse brings a fated encounter with someone from a different background.'),
('Aries', 3, 'Money', 'Financial clarity arrives; you resolve a long-standing debt or tax issue.'),
('Aries', 3, 'Career', 'A sudden shift in your professional direction offers a chance to lead a new creative team.'),
('Aries', 3, 'Family', 'Sibling communication is vital; you may need to mediate a small dispute.'),
('Aries', 3, 'Health', 'Focus on your head and face; a visit to the dentist or eye doctor is recommended.'),
('Aries', 4, 'Love', 'Retrograde energy suggests a past lover may resurface. Think before responding.'),
('Aries', 4, 'Money', 'Avoid major purchases; focus on auditing your subscriptions and small leaks.'),
('Aries', 4, 'Career', 'A slow month for new projects; use this time to refine your existing portfolio.'),
('Aries', 4, 'Family', 'A parent or older relative may require your technical assistance or advice.'),
('Aries', 4, 'Health', 'Spring allergies may hit hard; prioritize respiratory health and clean air.'),
('Aries', 5, 'Love', 'Passion returns. A short trip with a partner reignites the initial spark.'),
('Aries', 5, 'Money', 'A bonus or unexpected gift arrives. Your side hustle begins to show real profit.'),
('Aries', 5, 'Career', 'You win a competitive bid or a high-stakes presentation. Your confidence is high.'),
('Aries', 5, 'Family', 'A joyful celebration at home. You might host a dinner for close friends.'),
('Aries', 5, 'Health', 'Strength training shows great results; you feel physically robust and capable.'),
('Aries', 6, 'Love', 'Communication is effortless. You and your partner are perfectly in sync.'),
('Aries', 6, 'Money', 'Focus on long-term savings. A financial advisor gives you a winning tip.'),
('Aries', 6, 'Career', 'A leadership role is offered. Your ability to take quick action is recognized.'),
('Aries', 6, 'Family', 'Minor repairs around the house are completed, bringing a sense of order.'),
('Aries', 6, 'Health', 'Keep your schedule light to avoid nervous exhaustion. Prioritize sleep.'),
('Aries', 7, 'Love', 'Jupiter enters Leo! This starts your most romantic year in over a decade.'),
('Aries', 7, 'Money', 'Income from creative ventures or hobbies begins to show significant profit.'),
('Aries', 7, 'Career', 'Your leadership style is celebrated. A promotion or high-profile role is offered.'),
('Aries', 7, 'Family', 'Joyful news regarding children or younger family members brings the household together.'),
('Aries', 7, 'Health', 'Energy is at an all-time high. Perfect for starting a competitive sport.'),
('Aries', 8, 'Love', 'The eclipse forces you to look at your social circle. A friend may become more.'),
('Aries', 8, 'Money', 'High expenses related to leisure; keep an eye on your credit card balance.'),
('Aries', 8, 'Career', 'A project stalls due to external factors. Be patient and wait for September.'),
('Aries', 8, 'Family', 'Family drama is possible near the 28th. Stay neutral and be the listener.'),
('Aries', 8, 'Health', 'Watch for heart palpitations or heat-related stress. Stay cool and hydrated.'),
('Aries', 9, 'Love', 'A stable, grounded relationship brings comfort. You value reliability now.'),
('Aries', 9, 'Money', 'Excellent month for a salary negotiation or finding a new high-paying client.'),
('Aries', 9, 'Career', 'Attention to detail is your superpower. You catch an error that saves the company.'),
('Aries', 9, 'Family', 'Routine home life is peaceful. You find joy in the "boring" daily chores.'),
('Aries', 9, 'Health', 'A great time for a medical check-up or starting a new dietary regime.'),
('Aries', 10, 'Love', 'Intimacy deepens. You share secrets that bring you closer than ever.'),
('Aries', 10, 'Money', 'A windfall from an investment or inheritance is possible. Manage it wisely.'),
('Aries', 10, 'Career', 'You are tasked with a secret or sensitive project. Your discretion is tested.'),
('Aries', 10, 'Family', 'Deep emotional healing within the family. An old wound finally closes.'),
('Aries', 10, 'Health', 'Focus on reproductive and hormonal health. Listen to your body''s rhythms.'),
('Aries', 11, 'Love', 'A sense of adventure enters your love life. Plan a getaway or try a new hobby.'),
('Aries', 11, 'Money', 'Funds for travel or education are easily found. Luck is on your side.'),
('Aries', 11, 'Career', 'A connection from abroad or a different industry opens a major door.'),
('Aries', 11, 'Family', 'Family discussions turn toward the future and long-term goals.'),
('Aries', 11, 'Health', 'Excellent month for outdoor activities. Your stamina is notably high.'),
('Aries', 12, 'Love', 'The year ends with a grand romantic gesture. You feel truly cherished.'),
('Aries', 12, 'Money', 'Generosity is the theme. You spend on others but end the year financially solid.'),
('Aries', 12, 'Career', 'Public recognition for your year-long efforts. A prestigious award is possible.'),
('Aries', 12, 'Family', 'The holidays are spent in a grand family reunion. You are the life of the party.'),
('Aries', 12, 'Health', 'You feel revitalized. A positive outlook boosts your overall well-being.');

-- LEO 2026
INSERT INTO zodiac_predictions_2026 (sign, month_id, category, prediction) VALUES 
('Leo', 3, 'Love', 'The eclipse tests your intimacy levels. Honesty is the only way forward.'),
('Leo', 3, 'Money', 'A partner''s financial situation changes, requiring a budget adjustment.'),
('Leo', 3, 'Career', 'A pivot toward a more creative or public-facing role begins now.'),
('Leo', 3, 'Family', 'Secrets regarding an inheritance or family asset may be revealed.'),
('Leo', 3, 'Health', 'Prioritize rest; your body is undergoing a deep energetic shift.'),
('Leo', 4, 'Love', 'A romantic interest from your past or a foreign land catches your eye.'),
('Leo', 4, 'Money', 'Wait until late month to sign any major financial contracts.'),
('Leo', 4, 'Career', 'A project involving international travel or publishing is delayed.'),
('Leo', 4, 'Family', 'Communication with distant relatives brings nostalgic but mixed feelings.'),
('Leo', 4, 'Health', 'Focus on your hips and thighs; regular stretching is highly beneficial.'),
('Leo', 5, 'Love', 'Your charisma is at an all-time high. Singles find a powerful attraction.'),
('Leo', 5, 'Money', 'Professional success leads to a significant increase in your net worth.'),
('Leo', 5, 'Career', 'A career peak month. You are promoted or given a massive new responsibility.'),
('Leo', 5, 'Family', 'Your success is celebrated by the family. A joyful gathering is likely.'),
('Leo', 5, 'Health', 'Your energy is boundless, but don''t overcommit to social engagements.'),
('Leo', 6, 'Love', 'A friend may confess feelings for you. The boundary of love and friendship blurs.'),
('Leo', 6, 'Money', 'Lucrative opportunities come through your professional network.'),
('Leo', 6, 'Career', 'Collaborative projects are favored. You lead a team to a major victory.'),
('Leo', 6, 'Family', 'A time of peace and harmony. Your home is a hub for social activity.'),
('Leo', 6, 'Health', 'Focus on group fitness; the social aspect of exercise keeps you motivated.'),
('Leo', 7, 'Love', 'Jupiter in Leo! The ultimate year for love begins. proposals are frequent.'),
('Leo', 7, 'Money', 'A financial windfall or a high-paying contract arrives as Jupiter enters your sign.'),
('Leo', 7, 'Career', 'You are the undisputed authority. Every proposal you submit is green-lit.'),
('Leo', 7, 'Family', 'You celebrate a major personal milestone with a lavish family gathering.'),
('Leo', 7, 'Health', 'You radiate vitality. Physical confidence is at its peak.'),
('Leo', 8, 'Love', 'The eclipse forces you to balance your ego with your partner''s needs.'),
('Leo', 8, 'Money', 'Large expenses on luxury items; ensure they are worth the long-term cost.'),
('Leo', 8, 'Career', 'Expect some delays or "behind the scenes" politics. Stay above the fray.'),
('Leo', 8, 'Family', 'A family member may be sensitive. Patience is your greatest tool.'),
('Leo', 8, 'Health', 'Watch for heart palpitations or heat stress. Prioritize hydration.'),
('Leo', 9, 'Love', 'Practical love. You and your partner focus on building a future together.'),
('Leo', 9, 'Money', 'A highly profitable month. Your ability to negotiate pay is unmatched.'),
('Leo', 9, 'Career', 'A grounded approach to work leads to a solid, long-term contract.'),
('Leo', 9, 'Family', 'A focus on the "business" of the family—budgeting and planning.'),
('Leo', 9, 'Health', 'A great month for a detox or starting a new nutritional plan.'),
('Leo', 10, 'Love', 'Communication is flirtatious. A short trip rekindles the flame.'),
('Leo', 10, 'Money', 'Small wins add up. A secondary income stream becomes very reliable.'),
('Leo', 10, 'Career', 'Your voice carries weight. You might lead a seminar or write a keynote.'),
('Leo', 10, 'Family', 'Peace returns to the household. Helping a younger member brings joy.'),
('Leo', 10, 'Health', 'Watch for throat or vocal cord strain. Stay hydrated and rest.'),
('Leo', 11, 'Love', 'Deep domestic bliss. You find joy in quiet nights at home with a partner.'),
('Leo', 11, 'Money', 'Investment in property or home improvement pays off in equity.'),
('Leo', 11, 'Career', 'Working from home or on private projects proves most productive.'),
('Leo', 11, 'Family', 'A beautiful month for family traditions and interior decorating.'),
('Leo', 11, 'Health', 'Focus on your core and back. Yoga is highly recommended for Leos now.'),
('Leo', 12, 'Love', 'You end the year as the star of every party. Romance is everywhere.'),
('Leo', 12, 'Money', 'Generous bonuses and gifts. Your financial standing is remarkably high.'),
('Leo', 12, 'Career', 'Name and fame. Your professional reputation is at an all-time peak.'),
('Leo', 12, 'Family', 'A grand holiday celebration. You are the anchor of the family unit.'),
('Leo', 12, 'Health', 'Excellent vitality. You end 2026 feeling stronger than ever.');

-- SAGITTARIUS 2026
INSERT INTO zodiac_predictions_2026 (sign, month_id, category, prediction) VALUES 
('Sagittarius', 3, 'Love', 'A fated meeting through a friend or community group is likely.'),
('Sagittarius', 3, 'Money', 'Focus on collaborative finances. A joint venture shows promise.'),
('Sagittarius', 3, 'Career', 'A professional peak. You receive an award or a major public honor.'),
('Sagittarius', 3, 'Family', 'A change in your living situation or home environment is triggered.'),
('Sagittarius', 3, 'Health', 'Focus on your feet and immune system. Rest is non-negotiable.'),
('Sagittarius', 4, 'Love', 'A past lover may reach out. Determine if they fit your new path.'),
('Sagittarius', 4, 'Money', 'Be cautious with speculative investments. Stick to what you know.'),
('Sagittarius', 4, 'Career', 'A project involving creativity or children is temporarily stalled.'),
('Sagittarius', 4, 'Family', 'Misunderstandings with siblings or neighbors are likely. Be clear.'),
('Sagittarius', 4, 'Health', 'A great month for mental health check-ins and light cardio.'),
('Sagittarius', 5, 'Love', 'Relationship harmony. You and your partner enjoy a shared hobby.'),
('Sagittarius', 5, 'Money', 'A steady increase in daily income. Small freelance gigs add up.'),
('Sagittarius', 5, 'Career', 'Your professional reputation is solid. A new partnership is signed.'),
('Sagittarius', 5, 'Family', 'Home life is active and fun. You might plan a future family trip.'),
('Sagittarius', 5, 'Health', 'High energy levels. A great time to start a new fitness challenge.'),
('Sagittarius', 6, 'Love', 'Deep, soulful connection. You share your most secret dreams.'),
('Sagittarius', 6, 'Money', 'Commission-based work or royalties skyrocket. A debt is cleared.'),
('Sagittarius', 6, 'Career', 'Strategic alliances are formed. You work well behind the scenes.'),
('Sagittarius', 6, 'Family', 'A sensitive family matter is resolved through compassion.'),
('Sagittarius', 6, 'Health', 'Prioritize sleep and emotional well-being. Listen to your intuition.'),
('Sagittarius', 7, 'Love', 'Adventure in love! You meet someone through travel or education.'),
('Sagittarius', 7, 'Money', 'Funds for a major trip or school are easily secured.'),
('Sagittarius', 7, 'Career', 'Expansion. You take your business or project to an international level.'),
('Sagittarius', 7, 'Family', 'A joyful family reunion involves travel or distant relatives.'),
('Sagittarius', 7, 'Health', 'Excellent month for outdoor activities. Your stamina is high.'),
('Sagittarius', 8, 'Love', 'The eclipse brings a career-love conflict. Choose balance.'),
('Sagittarius', 8, 'Money', 'A sudden shift in your professional income. Be ready for change.'),
('Sagittarius', 8, 'Career', 'A major career transition. You may leave a role for a better one.'),
('Sagittarius', 8, 'Family', 'Your professional life impacts your home. Communicate with family.'),
('Sagittarius', 8, 'Health', 'Watch for stress-related headaches. Prioritize relaxation.'),
('Sagittarius', 9, 'Love', 'A friend may become a partner. Shared values are the foundation.'),
('Sagittarius', 9, 'Money', 'Financial gains come through social networking and groups.'),
('Sagittarius', 9, 'Career', 'A team project is a massive success. Your vision is validated.'),
('Sagittarius', 9, 'Family', 'A peaceful time with friends who feel like family.'),
('Sagittarius', 9, 'Health', 'Excellent month for group sports or a fitness community.'),
('Sagittarius', 10, 'Love', 'Privacy is valued. You enjoy a quiet, hidden romance.'),
('Sagittarius', 10, 'Money', 'A hidden or unexpected financial source is revealed.'),
('Sagittarius', 10, 'Career', 'Productive work behind the scenes. You prepare for a major launch.'),
('Sagittarius', 10, 'Family', 'Quiet time at home. You focus on inner reflection and family history.'),
('Sagittarius', 10, 'Health', 'A time for rest and rejuvenation. Focus on your spiritual health.'),
('Sagittarius', 11, 'Love', 'Happy birthday! You are the center of attention and highly magnetic.'),
('Sagittarius', 11, 'Money', 'Personal charisma leads to financial opportunities. Trust yourself.'),
('Sagittarius', 11, 'Career', 'A new personal project takes off. You are the boss of your destiny.'),
('Sagittarius', 11, 'Family', 'A family celebration in your honor brings deep joy.'),
('Sagittarius', 11, 'Health', 'A surge of physical vitality. You feel like a new person.'),
('Sagittarius', 12, 'Love', 'Deeply sensual and grounded. You value the simple joy of being together.'),
('Sagittarius', 12, 'Money', 'A very lucrative end to the year. Your income hits a 2026 high.'),
('Sagittarius', 12, 'Career', 'You finalize a major deal. Your professional standing is secure.'),
('Sagittarius', 12, 'Family', 'A cozy, high-quality holiday. You spoil your loved ones.'),
('Sagittarius', 12, 'Health', 'Physical stamina is excellent. You end the year on a health high.');
