-- MARCH - DECEMBER 2026: WATER SIGNS (Cancer, Scorpio, Pisces)
-- Categories: Love, Money, Career, Family, Health

-- CANCER 2026 (MARCH - DECEMBER)
INSERT INTO zodiac_predictions_2026 (sign, month_id, category, prediction) VALUES 
('Cancer', 3, 'Love', 'The eclipse highlights a fated relationship turning point.'),
('Cancer', 3, 'Money', 'A sudden shift in joint finances or a partner''s income.'),
('Cancer', 3, 'Career', 'A professional breakthrough through partnership.'),
('Cancer', 3, 'Family', 'Secrets regarding an inheritance or family asset revealed.'),
('Cancer', 3, 'Health', 'Prioritize your nervous system. Deep breathing is vital.'),
('Cancer', 4, 'Love', 'Career/Love balance is slow. Revisit old professional plans.'),
('Cancer', 4, 'Money', 'Wait until late month to finalize major career financial deals.'),
('Cancer', 4, 'Career', 'High-stakes projects delayed. Use time for fine-tuning.'),
('Cancer', 4, 'Family', 'Misunderstandings with a parent or professional figure.'),
('Cancer', 4, 'Health', 'Watch for stress headaches. Prioritize relaxation.'),
('Cancer', 5, 'Love', 'Social life vibrant. Meet someone through a group.'),
('Cancer', 5, 'Money', 'Profitable networking. Friend provides a financial tip.'),
('Cancer', 5, 'Career', 'Collaborative projects a success. Key team player.'),
('Cancer', 5, 'Family', 'Joyful events with extended family or community.'),
('Cancer', 5, 'Health', 'Group fitness keeps you motivated and healthy.'),
('Cancer', 6, 'Love', 'Happy birthday! Final month of Jupiter in Cancer. Proposals.'),
('Cancer', 6, 'Money', 'Financial gifts or bonuses. Personal brand brings profit.'),
('Cancer', 6, 'Career', 'A major breakthrough. Boss of your own destiny.'),
('Cancer', 6, 'Family', 'You focus of celebrations. Harmonious family month.'),
('Cancer', 6, 'Health', 'Vitality returns. Physical makeover or new diet.'),
('Cancer', 7, 'Love', 'Sensual and grounded. Quality time with a partner.'),
('Cancer', 7, 'Money', 'Highly profitable month. Your income increases.'),
('Cancer', 7, 'Career', 'Practical skills in demand. Finalize a solid deal.'),
('Cancer', 7, 'Family', 'Focus on home security and stability. Peaceful.'),
('Cancer', 7, 'Health', 'Excellent stamina. Focus on neck and throat.'),
('Cancer', 8, 'Love', 'The eclipse forces a look at your communication and love.'),
('Cancer', 8, 'Money', 'Large expenses on gadgets or local travel. Budget.'),
('Cancer', 8, 'Career', 'Expect some delays in marketing or writing. Fine-tune.'),
('Cancer', 8, 'Family', 'Misunderstandings with siblings or neighbors.'),
('Cancer', 8, 'Health', 'Watch for throat or vocal cord strain. Rest.'),
('Cancer', 9, 'Love', 'Deeply emotional and cozy. Home joy with a partner.'),
('Cancer', 9, 'Money', 'Beautiful month for home improvement and value.'),
('Cancer', 9, 'Career', 'Working from home or privately proves very productive.'),
('Cancer', 9, 'Family', 'Harmonious home life. Family traditions are joy.'),
('Cancer', 9, 'Health', 'Focus on core and back. Yoga is recommended.'),
('Cancer', 10, 'Love', 'Romantic and fun! Dates, hobbies, and creativity.'),
('Cancer', 10, 'Money', 'Luck is on your side. Small win or creative profit.'),
('Cancer', 10, 'Career', 'A creative project is a success. Professional praise.'),
('Cancer', 10, 'Family', 'Joyful news regarding family growth or kids.'),
('Cancer', 10, 'Health', 'Great month for fun fitness—dance or group sports.'),
('Cancer', 11, 'Love', 'Commitment is the theme. Work toward a shared goal.'),
('Cancer', 11, 'Money', 'Steady financial gains through joint ventures.'),
('Cancer', 11, 'Career', 'Meticulous attention to detail earns you high praise.'),
('Cancer', 11, 'Family', 'Routine home life is peaceful. Joy in daily tasks.'),
('Cancer', 11, 'Health', 'Focus on gut health. Medical check-up favored.'),
('Cancer', 12, 'Love', 'Deep intimacy. You and your partner share a bond.'),
('Cancer', 12, 'Money', 'A windfall from a joint source or investment.'),
('Cancer', 12, 'Career', 'Strategic work behind the scenes. Handle secrets well.'),
('Cancer', 12, 'Family', 'Deep emotional healing. A long-standing issue resolved.'),
('Cancer', 12, 'Health', 'Focus on hormonal balance and reproductive health.');

-- SCORPIO 2026 (MARCH - DECEMBER)
INSERT INTO zodiac_predictions_2026 (sign, month_id, category, prediction) VALUES 
('Scorpio', 3, 'Love', 'The eclipse highlights a fated meeting or passion project.'),
('Scorpio', 3, 'Money', 'A sudden shift in speculative income. Be ready for change.'),
('Scorpio', 3, 'Career', 'A creative project is a success. Praised for vision.'),
('Scorpio', 3, 'Family', 'Joyful news regarding children or family expansion.'),
('Scorpio', 3, 'Health', 'Energy is high. Perfect for team sports or fun.'),
('Scorpio', 4, 'Love', 'Relationship communication is slow. Revisit old agreements.'),
('Scorpio', 4, 'Money', 'Wait until late month to finalize major joint financial deals.'),
('Scorpio', 4, 'Career', 'Partnership projects are delayed. Fine-tune your role.'),
('Scorpio', 4, 'Family', 'Misunderstandings with a spouse or close family member.'),
('Scorpio', 4, 'Health', 'Focus on gut health and routine. A gentle detox favored.'),
('Scorpio', 5, 'Love', 'Commitment deepens. Work toward a shared goal.'),
('Scorpio', 5, 'Money', 'Steady financial gains through partnership or ventures.'),
('Scorpio', 5, 'Career', 'Meticulous attention to detail earns you high praise.'),
('Scorpio', 5, 'Family', 'Routine home life is peaceful. Joy in daily tasks.'),
('Scorpio', 5, 'Health', 'Focus on routine and medical check-ups.'),
('Scorpio', 6, 'Love', 'Deep intimacy. You and partner share a profound bond.'),
('Scorpio', 6, 'Money', 'Windfall from joint source or investment likely.'),
('Scorpio', 6, 'Career', 'Strategic work behind scenes. Handle sensitivity well.'),
('Scorpio', 6, 'Family', 'Deep emotional healing. Long-standing issue resolved.'),
('Scorpio', 6, 'Health', 'Focus on hormonal balance and reproductive health.'),
('Scorpio', 7, 'Love', 'Expansion through travel or learning with partner.'),
('Scorpio', 7, 'Money', 'Income from foreign source or teaching increases.'),
('Scorpio', 7, 'Career', 'Success in publishing, travel, or legal. Fame.'),
('Scorpio', 7, 'Family', 'Joyful family trip or event involving distance.'),
('Scorpio', 7, 'Health', 'Energy is high. Perfect for outdoor activities.'),
('Scorpio', 8, 'Love', 'The eclipse forces a career/love choice. Truth.'),
('Scorpio', 8, 'Money', 'A sudden shift in professional income. Ready for change.'),
('Scorpio', 8, 'Career', 'A major career transition. Leave a role for better.'),
('Scorpio', 8, 'Family', 'Professional life impacts home. Communicate.'),
('Scorpio', 8, 'Health', 'Watch for stress headaches. Relaxation.'),
('Scorpio', 9, 'Love', 'Social life vibrant. Meet someone through a group.'),
('Scorpio', 9, 'Money', 'Profitable networking. High-value financial tip.'),
('Scorpio', 9, 'Career', 'Collaborative projects a success. Key team player.'),
('Scorpio', 9, 'Family', 'Joyful events with extended family.'),
('Scorpio', 9, 'Health', 'Group fitness keeps you motivated and healthy.'),
('Scorpio', 10, 'Love', 'Happy birthday! You are magnetic and attracting interest.'),
('Scorpio', 10, 'Money', 'Financial gifts or bonuses. Personal brand profit.'),
('Scorpio', 10, 'Career', 'Major breakthrough. Boss of your own destiny.'),
('Scorpio', 10, 'Family', 'You focus of celebrations. Harmonious month.'),
('Scorpio', 10, 'Health', 'Vitality returns. Physical makeover or new diet.'),
('Scorpio', 11, 'Love', 'Sensual and grounded. Quality time with partner.'),
('Scorpio', 11, 'Money', 'Highly profitable month. Income increases.'),
('Scorpio', 11, 'Career', 'Practical skills in demand. Finalize solid deal.'),
('Scorpio', 11, 'Family', 'Focus on home security and stability. Peaceful.'),
('Scorpio', 11, 'Health', 'Excellent stamina. Focus on neck and throat.'),
('Scorpio', 12, 'Love', 'A short trip brings romance. Communication is deep.'),
('Scorpio', 12, 'Money', 'Small wins add up. Secondary income is reliable.'),
('Scorpio', 12, 'Career', 'Ideas valued. Great for marketing and writing.'),
('Scorpio', 12, 'Family', 'Peace returns home. Helping younger member joy.'),
('Scorpio', 12, 'Health', 'Light cardio and fresh air. Healthy end to 2026.');

-- PISCES 2026 (MARCH - DECEMBER)
INSERT INTO zodiac_predictions_2026 (sign, month_id, category, prediction) VALUES 
('Pisces', 3, 'Love', 'The eclipse in your sign brings a fated life decision.'),
('Pisces', 3, 'Money', 'Sudden shift in personal finances. Caution with spending.'),
('Pisces', 3, 'Career', 'Major breakthrough. You are the center of attention.'),
('Pisces', 3, 'Family', 'Family secrets surface. Analytical skills solve them.'),
('Pisces', 3, 'Health', 'Prioritize nervous system. Breathing and rest vital.'),
('Pisces', 4, 'Love', 'Financial communication with partner slow. Revisit plans.'),
('Pisces', 4, 'Money', 'Wait until late month to sign personal financial deals.'),
('Pisces', 4, 'Career', 'Daily work tasks delayed. Refine your routine.'),
('Pisces', 4, 'Family', 'Misunderstandings regarding daily household tasks.'),
('Pisces', 4, 'Health', 'Focus on feet and immune system. Rest is non-negotiable.'),
('Pisces', 5, 'Love', 'A short trip brings romance. Communication deep.'),
('Pisces', 5, 'Money', 'Small wins add up. Secondary income reliable.'),
('Pisces', 5, 'Career', 'Ideas valued. Great for marketing and writing.'),
('Pisces', 5, 'Family', 'Peace returns home. Helping younger member joy.'),
('Pisces', 5, 'Health', 'Light cardio and fresh air. Stay active.'),
('Pisces', 6, 'Love', 'Deeply emotional and cozy. Home joy with partner.'),
('Pisces', 6, 'Money', 'Beautiful month for home improvement and value.'),
('Pisces', 6, 'Career', 'Working from home or privately proves productive.'),
('Pisces', 6, 'Family', 'Harmonious home life. Family traditions joy.'),
('Pisces', 6, 'Health', 'Focus on core and back. Yoga is recommended.'),
('Pisces', 7, 'Love', 'Romantic and fun! Dates, hobbies, and creativity.'),
('Pisces', 7, 'Money', 'Luck on your side. Small win or creative profit.'),
('Pisces', 7, 'Career', 'Creative project success. Professional praise.'),
('Pisces', 7, 'Family', 'Joyful news regarding family growth or kids.'),
('Pisces', 7, 'Health', 'Great month for fun fitness—dance or group sports.'),
('Pisces', 8, 'Love', 'The eclipse forces relationship turning point. Honesty.'),
('Pisces', 8, 'Money', 'Financial tension with partner. Keep accounts clear.'),
('Pisces', 8, 'Career', 'Partner or collaborator exits. Opens better door.'),
('Pisces', 8, 'Family', 'Home life requires delicate touch. Secret revealed.'),
('Pisces', 8, 'Health', 'Stress affects digestion. Clean eating and meditation.'),
('Pisces', 9, 'Love', 'Commitment is theme. Work toward a shared goal.'),
('Pisces', 9, 'Money', 'Steady financial gains through joint ventures.'),
('Pisces', 9, 'Career', 'Meticulous attention to detail earns high praise.'),
('Pisces', 9, 'Family', 'Routine home life peaceful. Joy in daily tasks.'),
('Pisces', 9, 'Health', 'Focus on gut health. Medical check-up favored.'),
('Pisces', 10, 'Love', 'Deep intimacy. You and partner share a bond.'),
('Pisces', 10, 'Money', 'Windfall from joint source or investment.'),
('Pisces', 10, 'Career', 'Strategic work behind scenes. Handle secrets well.'),
('Pisces', 10, 'Family', 'Deep emotional healing. Long-standing issue resolved.'),
('Pisces', 10, 'Health', 'Focus on hormonal balance and reproductive health.'),
('Pisces', 11, 'Love', 'Expansion through shared travel or learning.'),
('Pisces', 11, 'Money', 'Income from foreign source or teaching increases.'),
('Pisces', 11, 'Career', 'Success in publishing, travel, or legal fields.'),
('Pisces', 11, 'Family', 'Joyful family trip or event involving distance.'),
('Pisces', 11, 'Health', 'Energy is high. Perfect for outdoor activities.'),
('Pisces', 12, 'Love', 'Career success adds to your charisma. Romance.'),
('Pisces', 12, 'Money', 'Professional bonus or raise. Net worth grows.'),
('Pisces', 12, 'Career', 'Breakthrough month. Reach new career height.'),
('Pisces', 12, 'Family', 'Your success celebrated. Harmonious atmosphere.'),
('Pisces', 12, 'Health', 'Physical vitality at peak. Strong and capable.');
