-- MARCH - DECEMBER 2026: EARTH SIGNS (Taurus, Virgo, Capricorn)
-- Categories: Love, Money, Career, Family, Health

-- TAURUS 2026 (MARCH - DECEMBER)
INSERT INTO zodiac_predictions_2026 (sign, month_id, category, prediction) VALUES 
('Taurus', 3, 'Love', 'The eclipse highlights a friendship that may turn into something deeper.'),
('Taurus', 3, 'Money', 'A sudden change in your social or group-related expenses. Budget carefully.'),
('Taurus', 3, 'Career', 'Networking brings a major opportunity. A friend recommends you for a role.'),
('Taurus', 3, 'Family', 'A joyful event involving friends who are like family.'),
('Taurus', 3, 'Health', 'Focus on your ankles and circulation. Regular walks are beneficial.'),
('Taurus', 4, 'Love', 'Private feelings resurface. You may spend time reflecting on an ex.'),
('Taurus', 4, 'Money', 'A secret financial opportunity may arise. Keep it quiet for now.'),
('Taurus', 4, 'Career', 'Work behind the scenes is most productive. Avoid the spotlight.'),
('Taurus', 4, 'Family', 'Quiet time at home. You find peace in your own company or small circle.'),
('Taurus', 4, 'Health', 'Prioritize rest and mental health. Meditation is a key tool this month.'),
('Taurus', 5, 'Love', 'Happy birthday! You are radiant and attracting new romantic interest.'),
('Taurus', 5, 'Money', 'Financial gifts or bonuses are likely. Your personal brand brings profit.'),
('Taurus', 5, 'Career', 'A major breakthrough. You are given the green light for a personal project.'),
('Taurus', 5, 'Family', 'You are the focus of family celebrations. A very harmonious month.'),
('Taurus', 5, 'Health', 'Vitality returns. A great time for a physical makeover or new diet.'),
('Taurus', 6, 'Love', 'Sensual and grounded. You enjoy quality time and physical touch.'),
('Taurus', 6, 'Money', 'A highly profitable month. Your income increases significantly.'),
('Taurus', 6, 'Career', 'Your practical skills are in high demand. You finalize a solid deal.'),
('Taurus', 6, 'Family', 'Focus on home security and stability. A peaceful atmosphere prevails.'),
('Taurus', 6, 'Health', 'Excellent stamina. Focus on neck and throat health. Stay hydrated.'),
('Taurus', 7, 'Love', 'A short trip brings romance. Communication with a partner is soulful.'),
('Taurus', 7, 'Money', 'Small wins add up. A secondary income stream becomes reliable.'),
('Taurus', 7, 'Career', 'Your ideas are highly valued. A great month for marketing and writing.'),
('Taurus', 7, 'Family', 'Peace returns to the household. Helping a younger member brings joy.'),
('Taurus', 7, 'Health', 'A great month for light cardio and fresh air. Stay active.'),
('Taurus', 8, 'Love', 'The eclipse forces a look at your home life and partnership balance.'),
('Taurus', 8, 'Money', 'Large expenses related to property or family. Check your insurance.'),
('Taurus', 8, 'Career', 'A career transition is possible. You may change your work environment.'),
('Taurus', 8, 'Family', 'A sudden move or renovation. Family members may be restless.'),
('Taurus', 8, 'Health', 'Watch for stress-related digestive issues. Prioritize clean eating.'),
('Taurus', 9, 'Love', 'Romantic and fun! You enjoy dates, hobbies, and creativity.'),
('Taurus', 9, 'Money', 'Luck is on your side. A small win or creative venture pays off.'),
('Taurus', 9, 'Career', 'A creative project is a success. You are praised for your unique vision.'),
('Taurus', 9, 'Family', 'Joyful news regarding children or family expansion.'),
('Taurus', 9, 'Health', 'A great month for fun fitness—dance or team sports.'),
('Taurus', 10, 'Love', 'Commitment is the theme. You and a partner work toward a shared goal.'),
('Taurus', 10, 'Money', 'Steady financial gains through partnership or joint ventures.'),
('Taurus', 10, 'Career', 'Meticulous attention to detail earns you high praise from superiors.'),
('Taurus', 10, 'Family', 'A routine home life is peaceful. You find joy in daily tasks.'),
('Taurus', 10, 'Health', 'Focus on gut health and routine. A medical check-up is favored.'),
('Taurus', 11, 'Love', 'Deep intimacy. You and your partner share a profound emotional bond.'),
('Taurus', 11, 'Money', 'A windfall from a joint source or investment is likely.'),
('Taurus', 11, 'Career', 'Strategic work behind the scenes. You handle a sensitive matter well.'),
('Taurus', 11, 'Family', 'Deep emotional healing at home. A long-standing issue is resolved.'),
('Taurus', 11, 'Health', 'Focus on hormonal balance and reproductive health. Listen to your body.'),
('Taurus', 12, 'Love', 'Expansion through shared travel or philosophy. A fated meeting abroad.'),
('Taurus', 12, 'Money', 'Funds for travel or higher learning are secured easily.'),
('Taurus', 12, 'Career', 'You take your skills to a wider market. Success in international fields.'),
('Taurus', 12, 'Family', 'A holiday spent with diverse family or traveling together.'),
('Taurus', 12, 'Health', 'Physical stamina is high. You end the year feeling adventurous.');

-- VIRGO 2026 (MARCH - DECEMBER)
INSERT INTO zodiac_predictions_2026 (sign, month_id, category, prediction) VALUES 
('Virgo', 3, 'Love', 'The eclipse in your sign brings a fated relationship decision.'),
('Virgo', 3, 'Money', 'A sudden shift in your personal finances. Be cautious with spending.'),
('Virgo', 3, 'Career', 'A major professional breakthrough. You are the center of attention.'),
('Virgo', 3, 'Family', 'Family secrets may surface. Your analytical skills help solve them.'),
('Virgo', 3, 'Health', 'Prioritize your nervous system. Deep breathing and rest are vital.'),
('Virgo', 4, 'Love', 'Reflect on shared values with a partner. An old flame may reappear.'),
('Virgo', 4, 'Money', 'Wait until late month to sign major financial or joint contracts.'),
('Virgo', 4, 'Career', 'Research and planning are favored. Avoid a big project launch.'),
('Virgo', 4, 'Family', 'Communication with family is slow but meaningful. Revisit old issues.'),
('Virgo', 4, 'Health', 'A great month for a thorough medical check-up or detox.'),
('Virgo', 5, 'Love', 'Expansion through travel or learning with a partner. Romance blooms.'),
('Virgo', 5, 'Money', 'Income from a foreign source or high-level teaching increases.'),
('Virgo', 5, 'Career', 'Success in publishing, travel, or legal fields. You are recognized.'),
('Virgo', 5, 'Family', 'A joyful family trip or event involving a distant relative.'),
('Virgo', 5, 'Health', 'Energy is high. Perfect for outdoor activities and fresh air.'),
('Virgo', 6, 'Love', 'Career success adds to your charisma. A workplace romance is possible.'),
('Virgo', 6, 'Money', 'A professional bonus or raise is likely. Your net worth grows.'),
('Virgo', 6, 'Career', 'The "Golden Window." You reach a new height in your career.'),
('Virgo', 6, 'Family', 'Your success is celebrated. A very harmonious family atmosphere.'),
('Virgo', 6, 'Health', 'Physical vitality is at a peak. You feel strong and capable.'),
('Virgo', 7, 'Love', 'Social life is vibrant. You meet someone through a group or friend.'),
('Virgo', 7, 'Money', 'Profitable networking. A friend provides a high-value financial tip.'),
('Virgo', 7, 'Career', 'Collaborative projects are a success. You are a key team player.'),
('Virgo', 7, 'Family', 'Joyful events with your extended family or community.'),
('Virgo', 7, 'Health', 'Group fitness or team sports keep you motivated and healthy.'),
('Virgo', 8, 'Love', 'The eclipse forces a relationship turning point. Honesty is key.'),
('Virgo', 8, 'Money', 'Financial tension with a partner. Keep your personal accounts clear.'),
('Virgo', 8, 'Career', 'Expect a partner or collaborator to exit. It opens a better door.'),
('Virgo', 8, 'Family', 'Home life requires a delicate touch. A family secret is revealed.'),
('Virgo', 8, 'Health', 'Stress affects digestion. Prioritize clean eating and meditation.'),
('Virgo', 9, 'Love', 'Happy birthday! You are magnetic and attracting serious interest.'),
('Virgo', 9, 'Money', 'Financial gifts or bonuses. Your personal brand brings profit.'),
('Virgo', 9, 'Career', 'A major breakthrough. You are the boss of your own destiny.'),
('Virgo', 9, 'Family', 'You are the focus of celebrations. A very harmonious month.'),
('Virgo', 9, 'Health', 'Vitality returns. A great time for a physical makeover or diet.'),
('Virgo', 10, 'Love', 'Sensual and grounded. You enjoy quality time with a partner.'),
('Virgo', 10, 'Money', 'A highly profitable month. Your personal income increases.'),
('Virgo', 10, 'Career', 'Practical skills are in demand. You finalize a solid deal.'),
('Virgo', 10, 'Family', 'Focus on home security and stability. A peaceful atmosphere.'),
('Virgo', 10, 'Health', 'Excellent stamina. Focus on neck and throat. Stay hydrated.'),
('Virgo', 11, 'Love', 'A short trip brings romance. Communication with a partner is deep.'),
('Virgo', 11, 'Money', 'Small wins add up. A secondary income stream is reliable.'),
('Virgo', 11, 'Career', 'Your ideas are valued. Great for marketing, writing, and teaching.'),
('Virgo', 11, 'Family', 'Peace returns to the home. Helping a younger member brings joy.'),
('Virgo', 11, 'Health', 'A great month for light cardio and fresh air. Stay active.'),
('Virgo', 12, 'Love', 'Deeply emotional and cozy. You end the year with family joy.'),
('Virgo', 12, 'Money', 'Excellent year-end bonus. Your financial standing is secure.'),
('Virgo', 12, 'Career', 'You finalize a major project. Your professional status is solid.'),
('Virgo', 12, 'Family', 'A cozy, beautiful holiday at home. You are the master host.'),
('Virgo', 12, 'Health', 'You end 2026 feeling balanced and physically strong.');

-- CAPRICORN 2026 (MARCH - DECEMBER)
INSERT INTO zodiac_predictions_2026 (sign, month_id, category, prediction) VALUES 
('Capricorn', 3, 'Love', 'A fated relationship commitment. Engagement or marriage is possible.'),
('Capricorn', 3, 'Money', 'A sudden shift in joint finances or a partner''s income.'),
('Capricorn', 3, 'Career', 'A professional partnership is finalized. You have a solid ally.'),
('Capricorn', 3, 'Family', 'A change in your living environment or a sibling''s life.'),
('Capricorn', 3, 'Health', 'Focus on your knees and bones. Calcium and rest are needed.'),
('Capricorn', 4, 'Love', 'Reflect on past relationships. An ex may send a message.'),
('Capricorn', 4, 'Money', 'Avoid major purchases for the home until late in the month.'),
('Capricorn', 4, 'Career', 'Work behind the scenes is most productive. Refine your plans.'),
('Capricorn', 4, 'Family', 'Misunderstandings with parents or elders. Be patient and clear.'),
('Capricorn', 4, 'Health', 'Prioritize sleep and mental health. A great month for yoga.'),
('Capricorn', 5, 'Love', 'Romantic and fun! You enjoy dates and creative hobbies.'),
('Capricorn', 5, 'Money', 'Luck in speculative investments or creative ventures. Small wins.'),
('Capricorn', 5, 'Career', 'A creative project is a success. You are praised for your vision.'),
('Capricorn', 5, 'Family', 'Joyful news regarding children or a family celebration.'),
('Capricorn', 5, 'Health', 'Energy is high. Perfect for team sports or outdoor fun.'),
('Capricorn', 6, 'Love', 'Commitment deepens. You and a partner work toward a shared goal.'),
('Capricorn', 6, 'Money', 'Steady financial gains through partnership or joint ventures.'),
('Capricorn', 6, 'Career', 'Meticulous attention to detail earns you high praise.'),
('Capricorn', 6, 'Family', 'Routine home life is peaceful. You find joy in daily tasks.'),
('Capricorn', 6, 'Health', 'Focus on gut health and routine. A medical check-up is favored.'),
('Capricorn', 7, 'Love', 'Deep intimacy. You and your partner share a profound bond.'),
('Capricorn', 7, 'Money', 'A windfall from a joint source or investment is likely.'),
('Capricorn', 7, 'Career', 'Strategic work behind the scenes. You handle a sensitive matter well.'),
('Capricorn', 7, 'Family', 'Deep emotional healing at home. A long-standing issue resolved.'),
('Capricorn', 7, 'Health', 'Focus on hormonal balance and reproductive health.'),
('Capricorn', 8, 'Love', 'The eclipse forces a look at your beliefs and partnership.'),
('Capricorn', 8, 'Money', 'Large expenses on education or travel. Budget carefully.'),
('Capricorn', 8, 'Career', 'A transition in your professional direction or market.'),
('Capricorn', 8, 'Family', 'A family member may have a different vision for the future.'),
('Capricorn', 8, 'Health', 'Watch for stress-related headaches. Prioritize fresh air.'),
('Capricorn', 9, 'Love', 'Career success adds to your charisma. A workplace romance possible.'),
('Capricorn', 9, 'Money', 'A professional bonus or raise. Your net worth grows.'),
('Capricorn', 9, 'Career', 'A breakthrough month. You reach a new height in your career.'),
('Capricorn', 9, 'Family', 'Your success celebrated. A harmonious family atmosphere.'),
('Capricorn', 9, 'Health', 'Physical vitality at a peak. You feel strong and capable.'),
('Capricorn', 10, 'Love', 'Social life is vibrant. You meet someone through a group.'),
('Capricorn', 10, 'Money', 'Profitable networking. A friend provides a high-value tip.'),
('Capricorn', 10, 'Career', 'Collaborative projects successful. You are a key team player.'),
('Capricorn', 10, 'Family', 'Joyful events with your extended family or community.'),
('Capricorn', 10, 'Health', 'Group fitness keeps you motivated and healthy.'),
('Capricorn', 11, 'Love', 'Private feelings resurface. Enjoy quiet, hidden romance.'),
('Capricorn', 11, 'Money', 'A secret financial source is revealed. Keep it quiet.'),
('Capricorn', 11, 'Career', 'Work behind the scenes is most productive. Avoid spotlight.'),
('Capricorn', 11, 'Family', 'Quiet time at home. Inner reflection and family history.'),
('Capricorn', 11, 'Health', 'Prioritize rest and spiritual health. Meditation is key.'),
('Capricorn', 12, 'Love', 'Happy birthday! You end the year radiant and magnetic.'),
('Capricorn', 12, 'Money', 'Financial gifts or bonuses. Your personal brand brings profit.'),
('Capricorn', 12, 'Career', 'A major breakthrough. You are the boss of your destiny.'),
('Capricorn', 12, 'Family', 'You are the focus of celebrations. Harmonious holiday.'),
('Capricorn', 12, 'Health', 'Vitality returns. Physical makeover or new fitness plan.');
